export const CREATE_LOBBY_FAIL = "CREATE_LOBBY_FAIL";
export const CREATE_LOBBY_REQUEST = "CREATE_LOBBY_REQUEST";
export const CREATE_LOBBY_SUCCESS = "CREATE_LOBBY_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";