export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_REQUEST = "USER_DETAILS_RREQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";

export const USERNAME_EDIT_FAIL = "USERNAME_EDIT_FAIL";
export const USERNAME_EDIT_REQUEST = "USERNAME_EDIT_REQUEST";
export const USERNAME_EDIT_SUCCESS = "USERNAME_EDIT_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";